from enum import Enum

INNER_FIELD_ANGLE = 2
OUTER_FIELD_ANGLE = 80

DEPTH_VISION = 600

SIZE = WIDTH, HEIGHT = 1000, 600
BOX_PROPORTION = 0.4

MOVE_STEP = 4
ROTATION_STEP = 2
BULLET_STEP = 12
FIRE_DELAY = 100
BACKGROUND_COLOR = 255,255,255

WALL_SENSITIVITY = 10


REWARD_HIT_POSITIVE = 10
REWARD_HIT_NEGATIVE = -5
REWARD_ENEMY_SIGHT_OUTER = 0.005
REWARD_ENEMY_SIGHT_INNER = 0.01

SIMULATION_TIME = 800


class Observation(Enum):
	ENEMY_NOT_SIGHT = 0
	ENEMY_INNER_SIGHT = 1
	ENEMY_OUTER_LEFT_SIGHT = 2
	ENEMY_OUTER_RIGHT_SIGHT = 3

	BULLET_NOT_SIGHT = 4
	BULLET_INNER_SIGHT = 5
	BULLET_OUTER_LEFT_SIGHT = 6
	BULLET_OUTER_RIGHT_SIGHT = 7

	FIRE_READY = 8
	WALL = 9

class Actions(Enum):
	MOVE = 0
	MOVE_BACK = 1
	ROTATE_CLOCKWISE = 2
	ROTATE_COUNTERCLOCKWISE = 3
	MOVE_AND_ROTATE_CLOCKWISE = 4
	MOVE_AND_ROTATE_COUNTERCLOCKWISE = 5
	MOVE_BACK_AND_ROTATE_CLOCKWISE = 6
	MOVE_BACK_AND_ROTATE_COUNTERCLOCKWISE = 7
	FIRE = 8
	PASS = 9

