from enum import Enum

INNER_FIELD_ANGLE = 5
OUTER_FIELD_ANGLE = 80

DEPTH_VISION = 600

SIZE = WIDTH, HEIGHT = 1000, 600
BOX_PROPORTION = 0.4

MOVE_STEP = 4
ROTATION_STEP = 2
BULLET_STEP = 8
FIRE_DELAY = 80
BACKGROUND_COLOR = 255,255,255

WALL_SENSITIVITY = 10


REWARD_HIT_POSITIVE = 10
REWARD_HIT_NEGATIVE = 0
REWARD_ENEMY_SIGHT_OUTER = 0.005
REWARD_ENEMY_SIGHT_INNER = 0.01

SIMULATION_TIME = 800


class Observation(Enum):
	ENEMY_NOT_SIGHT = 0
	ENEMY_INNER_SIGHT = 1
	ENEMY_OUTER_LEFT_SIGHT = 2
	ENEMY_OUTER_RIGHT_SIGHT = 3

	BULLET_NOT_SIGHT = 4
	BULLET_INNER_SIGHT = 5
	BULLET_OUTER_LEFT_SIGHT = 6
	BULLET_OUTER_RIGHT_SIGHT = 7

	FIRE_READY = 8
	WALL = 9

class Actions(Enum):
	MOVE = 0
	ROTATE_CLOCKWISE = 1
	ROTATE_COUNTERCLOCKWISE = 2
	MOVE_AND_ROTATE_CLOCKWISE = 3
	MOVE_AND_ROTATE_COUNTERCLOCKWISE = 4
	FIRE = 5
	PASS = 6

